### ISSUE TITLE
conversation_open的时候报错cannot_dm_bot

### ISSUE THREAD

**Issue by johnnyeven** [yokonsan/claude-in-slack-api#4]
Traceback:

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/liyiwen/opt/anaconda3/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/liyiwen/opt/anaconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/liyiwen/opt/anaconda3/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/liyiwen/opt/anaconda3/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/liyiwen/opt/anaconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/liyiwen/opt/anaconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/liyiwen/opt/anaconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/liyiwen/opt/anaconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/liyiwen/opt/anaconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/liyiwen/opt/anaconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/liyiwen/opt/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/liyiwen/opt/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/liyiwen/opt/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/liyiwen/opt/anaconda3/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/Users/liyiwen/opt/anaconda3/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/liyiwen/Documents/python/claude-in-slack-api/./claude.py", line 30, in chat
    await client.open_channel()
  File "/Users/liyiwen/Documents/python/claude-in-slack-api/slack.py", line 27, in open_channel
    response = await self.conversations_open(users=CLAUDE_BOT_ID)
  File "/Users/liyiwen/opt/anaconda3/lib/python3.10/site-packages/slack_sdk/web/async_client.py", line 2684, in conversations_open
    return await self.api_call("conversations.open", params=kwargs)
  File "/Users/liyiwen/opt/anaconda3/lib/python3.10/site-packages/slack_sdk/web/async_base_client.py", line 161, in api_call
    return await self._send(
  File "/Users/liyiwen/opt/anaconda3/lib/python3.10/site-packages/slack_sdk/web/async_base_client.py", line 201, in _send
    return AsyncSlackResponse(**{**data, **res}).validate()
  File "/Users/liyiwen/opt/anaconda3/lib/python3.10/site-packages/slack_sdk/web/async_slack_response.py", line 203, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed. (url: https://www.slack.com/api/conversations.open)
The server responded with: {'ok': False, 'error': 'cannot_dm_bot'}

有没有可能现在已经不能这么玩儿了？

**Comment by johnnyeven** [comment]
补充一下，创建token的时候实际上有两个，一个是Bot user oauth token，另一个是user oauth token，需要的实际上是第二个。对应设置scope也有两个，这个地方要注意下，不要弄混了

**Comment by yokonsan** [comment]
> 补充一下，创建token的时候实际上有两个，一个是Bot user oauth token，另一个是user oauth token，需要的实际上是第二个。对应设置scope也有两个，这个地方要注意下，不要弄混了

教程文章说的应该很清楚了。。。

**Comment by Song345381185** [comment]
不好意思我有个地方看错了，还有个问题8088端口是可以修改的吗，我本地打不开生成的连接

**Comment by yokonsan** [comment]
> 不好意思我有个地方看错了，还有个问题8088端口是可以修改的吗，我本地打不开生成的连接

可以修改
